version: '3.1'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  data-redis:
    image: data-redis:0.0.1-SNAPSHOT
volumes:
  redis_data:
    driver: local